version: 0.2.0.{build}

environment:
  nodejs_version: "0.10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g grunt-cli
  - npm install

before_build:
  - appveyor DownloadFile "http://dl.google.com/closure-compiler/compiler-latest.zip" -FileName compiler-latest.zip
  - 7za e compiler-latest.zip closure
  
build_script:
  - grunt default

test_script:
  - grunt test

notifications:
  - provider: Slack
    auth_token:
      secure: PigIGGo7UUDwdb0KGM/s7OfpAng/OMJx7q33jKfzudFBiXi1EBEd0DRmkbCc7CiX
    channel: notifications
